version: '3'
services:
 db:
  image: mysql
  environment:
   - MYSQL_DATABASE=drupal
   - MYSQL_ROOT_PASSWORD=drupal
  volumes:
   - volumenDocker:/var/lib/mysql
 drupal:
  depends_on:
   - db
  ports:
   - "81:80"
  volumes:
   - volumenDocker:/app
volumes:
 volumenDocker:
